import { EnumLiteral } from '../typescript';

export interface HttpStatusState {
	name: HTTP_STATUS_CODE;
	code: HTTP_STATUS;
}

export const HTTP_STATUS = {
	CONTINUE: 100,
	OK: 200,
	CREATED: 201,
	ACCEPTED: 202,
	NON_AUTHORITATIVE: 203,
	NO_CONTENT: 204,
	MULTIPLE_CHOICE: 300,
	MOVED_PERMANENTLY: 301,
	FOUND: 302,
	BAD_REQUEST: 400,
	UNAUTHORIZED: 401,
	FORBIDDEN: 403,
	NOT_FOUND: 404,
	INTERNAL_SERVER_ERROR: 500,
	NOT_IMPLEMENTED: 501,
	BAD_GATEWAY: 502,
} as const;

export type HTTP_STATUS = EnumLiteral<typeof HTTP_STATUS>;
export type HTTP_STATUS_CODE = keyof typeof HTTP_STATUS;

export const HTTP_STATUS_BY_ID: Record<HTTP_STATUS, HttpStatusState> = {
	[HTTP_STATUS.CONTINUE]: {
		name: 'CONTINUE',
		code: HTTP_STATUS.CONTINUE,
	},
	[HTTP_STATUS.OK]: {
		name: 'OK',
		code: HTTP_STATUS.OK,
	},
	[HTTP_STATUS.CREATED]: {
		name: 'CREATED',
		code: HTTP_STATUS.CREATED,
	},
	[HTTP_STATUS.ACCEPTED]: {
		name: 'ACCEPTED',
		code: HTTP_STATUS.ACCEPTED,
	},
	[HTTP_STATUS.NON_AUTHORITATIVE]: {
		name: 'NON_AUTHORITATIVE',
		code: HTTP_STATUS.NON_AUTHORITATIVE,
	},
	[HTTP_STATUS.NO_CONTENT]: {
		name: 'NO_CONTENT',
		code: HTTP_STATUS.NO_CONTENT,
	},
	[HTTP_STATUS.MULTIPLE_CHOICE]: {
		name: 'MULTIPLE_CHOICE',
		code: HTTP_STATUS.MULTIPLE_CHOICE,
	},
	[HTTP_STATUS.MOVED_PERMANENTLY]: {
		name: 'MOVED_PERMANENTLY',
		code: HTTP_STATUS.MOVED_PERMANENTLY,
	},
	[HTTP_STATUS.FOUND]: {
		name: 'FOUND',
		code: HTTP_STATUS.FOUND,
	},
	[HTTP_STATUS.BAD_REQUEST]: {
		name: 'BAD_REQUEST',
		code: HTTP_STATUS.BAD_REQUEST,
	},
	[HTTP_STATUS.UNAUTHORIZED]: {
		name: 'UNAUTHORIZED',
		code: HTTP_STATUS.UNAUTHORIZED,
	},
	[HTTP_STATUS.FORBIDDEN]: {
		name: 'FORBIDDEN',
		code: HTTP_STATUS.FORBIDDEN,
	},
	[HTTP_STATUS.NOT_FOUND]: {
		name: 'NOT_FOUND',
		code: HTTP_STATUS.NOT_FOUND,
	},
	[HTTP_STATUS.INTERNAL_SERVER_ERROR]: {
		name: 'INTERNAL_SERVER_ERROR',
		code: HTTP_STATUS.INTERNAL_SERVER_ERROR,
	},
	[HTTP_STATUS.NOT_IMPLEMENTED]: {
		name: 'NOT_IMPLEMENTED',
		code: HTTP_STATUS.NOT_IMPLEMENTED,
	},
	[HTTP_STATUS.BAD_GATEWAY]: {
		name: 'BAD_GATEWAY',
		code: HTTP_STATUS.BAD_GATEWAY,
	},
};

export const HTTP_STATUS_LIST = Object.values(HTTP_STATUS_BY_ID);

export function getHttpStatusStateById(id: HTTP_STATUS): HttpStatusState {
	return HTTP_STATUS_BY_ID[id];
}
